version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: "no"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites.template:/etc/nginx/sites-available/sites.template
      - ./nginx/default/html:/var/www/html
      - ./data/log/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOSTNAME=${HOST_NAME:-lti.xlab.blindside-dev.com}
    depends_on:
      - broker
      - rooms
    command: /bin/bash -c "envsubst '$$NGINX_HOSTNAME' < /etc/nginx/sites-available/sites.template > /etc/nginx/sites-enabled/sites.conf && exec nginx -g 'daemon off;'"
    logging:
      driver: journald

  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: journald

  broker:
    image: ${DOCKER_REPO:-bigbluebutton}/bbb-lti-broker:${DOCKER_TAG:-latest}
    container_name: broker
    volumes:
      - ./broker/seeds.rb:/usr/src/app/db/seeds.rb
    env_file: broker/.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432}/bbb_lti_broker_production
    ports:
      - "3001:3000"
    links:
      - postgres
    logging:
      driver: journald

  rooms:
    image: ${DOCKER_REPO:-bigbluebutton}/bbb-app-rooms:${DOCKER_TAG:-latest}
    container_name: rooms
    env_file: rooms/.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432}/bbb_lti_rooms_production
    ports:
      - "3002:3000"
    links:
      - postgres
    logging:
      driver: journald
